# Generated by Django 5.0.3 on 2025-12-11 17:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stockman', '0005_alter_hold_options_alter_move_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_id', models.PositiveIntegerField(help_text='ID do produto de saída', verbose_name='ID do Produto')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Quantidade produzida por execução da receita', max_digits=10, verbose_name='Quantidade de Saída')),
                ('code', models.SlugField(help_text='Identificador único (ex: croissant-v1)', unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nome legível da receita', max_length=200, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Receita pode ser usada para novas ordens', verbose_name='Ativa')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Tempo estimado de produção', null=True, verbose_name='Duração (minutos)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais: steps, equipment, skill_level, etc.', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type', models.ForeignKey(help_text='Tipo do produto de saída', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'craftsman_recipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.PositiveIntegerField(help_text='ID do material de entrada', verbose_name='ID do Insumo')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade necessária por execução', max_digits=10, verbose_name='Quantidade')),
                ('is_alternative', models.BooleanField(default=False, help_text='Pode ser substituído por outro no grupo', verbose_name='É Alternativa')),
                ('alternative_group', models.CharField(blank=True, help_text='Nome do grupo (ex: gordura)', max_length=50, verbose_name='Grupo de Alternativas')),
                ('input_type', models.ForeignKey(help_text='Tipo do material de entrada', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Insumo')),
                ('position', models.ForeignKey(blank=True, help_text='De onde buscar o material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockman.position', verbose_name='Posição')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='craftsman.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Insumo da Receita',
                'verbose_name_plural': 'Insumos da Receita',
                'db_table': 'craftsman_recipe_input',
                'ordering': ['recipe', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador único (ex: WO-2025-00001)', max_length=50, unique=True, verbose_name='Código')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade a produzir', max_digits=10, verbose_name='Quantidade Planejada')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade efetivamente produzida', max_digits=10, null=True, verbose_name='Quantidade Real')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Produção'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Início Agendado')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim Agendado')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Início Real')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim Real')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Origem')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais: completed_steps, step_log, etc.', verbose_name='Metadados')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('destination', models.ForeignKey(help_text='Onde entregar o produto final', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_delivered', to='stockman.position', verbose_name='Destino')),
                ('location', models.ForeignKey(blank=True, help_text='Onde o trabalho acontece (workstation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_executed', to='stockman.position', verbose_name='Local de Produção')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='craftsman.recipe', verbose_name='Receita')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Origem')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'db_table': 'craftsman_work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['code'], name='craftsman_r_code_fd8684_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_active'], name='craftsman_r_is_acti_27364d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['output_type', 'output_id'], name='craftsman_r_output__f4f6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeinput',
            index=models.Index(fields=['recipe'], name='craftsman_r_recipe__06ac34_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeinput',
            index=models.Index(fields=['input_type', 'input_id'], name='craftsman_r_input_t_f58979_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'scheduled_start'], name='craftsman_w_status_67f347_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['recipe', 'status'], name='craftsman_w_recipe__1ef786_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['location', 'status'], name='craftsman_w_locatio_cf412e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_start'], name='craftsman_w_schedul_8a0500_idx'),
        ),
    ]
