# Generated by Django 5.0.3 on 2026-02-21 02:45

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# Like AUTH_USER_MODEL, CRAFTSMAN_POSITION_MODEL must resolve at import time.
# Provide default for projects that haven't configured it yet.
CRAFTSMAN_POSITION_MODEL = getattr(
    settings, "CRAFTSMAN_POSITION_MODEL", "craftsman.Position"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(CRAFTSMAN_POSITION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'db_table': 'craftsman_position',
                'swappable': 'CRAFTSMAN_POSITION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Insumo',
                'verbose_name_plural': 'Categorias de Insumos',
                'db_table': 'craftsman_ingredient_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('date', models.DateField(help_text='Data em que a produção acontecerá', unique=True, verbose_name='Data de Produção')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('scheduled', 'Agendado'), ('completed', 'Concluído')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plano de Produção',
                'verbose_name_plural': 'Planos de Produção',
                'db_table': 'craftsman_plan',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('date', models.DateField(db_index=True, help_text='Data em que a produção acontecerá', verbose_name='Data de Produção')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('scheduled', 'Agendado'), ('completed', 'Concluído')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Plano de Produção',
                'verbose_name_plural': 'historical Planos de Produção',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('output_id', models.PositiveIntegerField(help_text='ID do produto de saída', verbose_name='ID do Produto')),
                ('code', models.SlugField(help_text='Identificador único (ex: croissant-v1)', verbose_name='Código')),
                ('name', models.CharField(help_text='Nome legível da receita', max_length=200, verbose_name='Nome')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Quantidade produzida por execução da receita', max_digits=10, verbose_name='Quantidade de Saída')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, help_text='Dias de antecedência para iniciar produção', verbose_name='Lead Time (dias)')),
                ('steps', models.JSONField(blank=True, default=list, help_text="Lista de etapas: ['Mixing', 'Shaping', 'Baking']", verbose_name='Etapas de Produção')),
                ('is_active', models.BooleanField(default=True, help_text='Receita pode ser usada para novas ordens', verbose_name='Ativa')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Tempo estimado de produção total', null=True, verbose_name='Duração (minutos)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('output_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo do produto de saída', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Produto')),
                ('work_center', models.ForeignKey(blank=True, db_constraint=False, help_text='Posição onde a produção acontece', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=CRAFTSMAN_POSITION_MODEL, verbose_name='Centro de Trabalho')),
            ],
            options={
                'verbose_name': 'historical Receita',
                'verbose_name_plural': 'historical Receitas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('output_id', models.PositiveIntegerField(help_text='ID do produto de saída', verbose_name='ID do Produto')),
                ('code', models.SlugField(help_text='Identificador único (ex: croissant-v1)', unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nome legível da receita', max_length=200, verbose_name='Nome')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Quantidade produzida por execução da receita', max_digits=10, verbose_name='Quantidade de Saída')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, help_text='Dias de antecedência para iniciar produção', verbose_name='Lead Time (dias)')),
                ('steps', models.JSONField(blank=True, default=list, help_text="Lista de etapas: ['Mixing', 'Shaping', 'Baking']", verbose_name='Etapas de Produção')),
                ('is_active', models.BooleanField(default=True, help_text='Receita pode ser usada para novas ordens', verbose_name='Ativa')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Tempo estimado de produção total', null=True, verbose_name='Duração (minutos)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type', models.ForeignKey(help_text='Tipo do produto de saída', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Produto')),
                ('work_center', models.ForeignKey(blank=True, help_text='Posição onde a produção acontece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=CRAFTSMAN_POSITION_MODEL, verbose_name='Centro de Trabalho')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'craftsman_recipe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('quantity', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Quantidade aprovada para produzir', max_digits=10, verbose_name='Aprovado')),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Maior = mais prioritário', verbose_name='Prioridade')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, help_text='Onde entregar o produto final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to=CRAFTSMAN_POSITION_MODEL, verbose_name='Destino')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.plan', verbose_name='Plano')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='craftsman.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Item do Plano',
                'verbose_name_plural': 'Itens do Plano',
                'db_table': 'craftsman_plan_item',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(help_text='ID do material de entrada', verbose_name='ID do Insumo')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade para receita base', max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(default='kg', help_text='kg, L, un, g...', max_length=10, verbose_name='Unidade')),
                ('is_alternative', models.BooleanField(default=False, help_text='Pode ser substituído por outro no grupo', verbose_name='É Alternativa')),
                ('alternative_group', models.CharField(blank=True, help_text='Nome do grupo (ex: gordura)', max_length=50, verbose_name='Grupo de Alternativas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('category', models.ForeignKey(blank=True, help_text='Categoria para agrupamento (ex: Massa, Farinha)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_items', to='craftsman.ingredientcategory', verbose_name='Categoria')),
                ('item_type', models.ForeignKey(help_text='Tipo do material de entrada', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Insumo')),
                ('position', models.ForeignKey(blank=True, help_text='De onde buscar o material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=CRAFTSMAN_POSITION_MODEL, verbose_name='Posição')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Item da Receita',
                'verbose_name_plural': 'Itens da Receita',
                'db_table': 'craftsman_recipe_item',
                'ordering': ['recipe', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(blank=True, help_text='Identificador único (auto-gerado se vazio)', max_length=50, unique=True, verbose_name='Código')),
                ('planned_quantity', models.DecimalField(decimal_places=0, help_text='Quantidade planejada a produzir', max_digits=10, verbose_name='Planejado')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=0, help_text='Quantidade efetivamente produzida', max_digits=10, null=True, verbose_name='Quantidade Real')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Produção'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Início Agendado')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim Agendado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início Real')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim Real')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da Origem')),
                ('process_quantity', models.DecimalField(blank=True, decimal_places=0, help_text='Quantidade processada', max_digits=10, null=True, verbose_name='Processado')),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=0, help_text='Quantidade final produzida', max_digits=10, null=True, verbose_name='Saída')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais: step_log, completed_by, etc.', verbose_name='Metadados')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_by', models.CharField(blank=True, help_text="Ex: 'user:joao', 'system:scheduler', 'api:pdv-001'", max_length=255, verbose_name='Criado por')),
                ('external_ref', models.CharField(blank=True, help_text='ID no sistema de origem, quando aplicável', max_length=255, verbose_name='Referência Externa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('destination', models.ForeignKey(blank=True, help_text='Onde entregar o produto final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_delivered', to=CRAFTSMAN_POSITION_MODEL, verbose_name='Destino')),
                ('location', models.ForeignKey(blank=True, help_text='Onde o trabalho acontece (workstation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_executed', to=CRAFTSMAN_POSITION_MODEL, verbose_name='Local de Produção')),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders_set', to='craftsman.planitem', verbose_name='Item do Plano')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='craftsman.recipe', verbose_name='Receita')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Origem')),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'db_table': 'craftsman_work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['code'], name='craftsman_r_code_fd8684_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_active'], name='craftsman_r_is_acti_27364d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['output_type', 'output_id'], name='craftsman_r_output__f4f6aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planitem',
            unique_together={('plan', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['recipe'], name='craftsman_r_recipe__f5a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['item_type', 'item_id'], name='craftsman_r_item_ty_cc5f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['category'], name='craftsman_r_categor_5f665d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('recipe', 'item_type', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'scheduled_start'], name='craftsman_w_status_67f347_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['recipe', 'status'], name='craftsman_w_recipe__1ef786_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['location', 'status'], name='craftsman_w_locatio_cf412e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_start'], name='craftsman_w_schedul_8a0500_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['plan_item'], name='craftsman_w_plan_it_a638ee_idx'),
        ),
    ]
