# Generated by Django 5.2.11 on 2026-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalplan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Planejamento', 'verbose_name_plural': 'historical Planejamentos'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Categoria de Ingrediente', 'verbose_name_plural': 'Categorias de Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-date'], 'verbose_name': 'Planejamento', 'verbose_name_plural': 'Planejamentos'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'ordering': ['recipe', 'category', 'id'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agendado em'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='agendado em'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
