# Generated by Django 5.0.3 on 2025-12-12 19:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('craftsman', '0002_v23_plan_planitem_recipe_updates'),
        ('stockman', '0005_alter_hold_options_alter_move_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='plan_item',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='source_type',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='craftsman_w_plan_it_a638ee_idx',
            old_name='craftsman_w_plan_it_idx',
        ),
        migrations.AddField(
            model_name='workorder',
            name='baking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade após forneamento', max_digits=10, null=True, verbose_name='Forneamento'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mixing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade após mistura', max_digits=10, null=True, verbose_name='Mistura'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='shaping',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade após modelagem', max_digits=10, null=True, verbose_name='Modelagem'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='date',
            field=models.DateField(db_index=True, help_text='Data em que a produção acontecerá', verbose_name='Data de Produção'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='code',
            field=models.SlugField(help_text='Identificador único (ex: croissant-v1)', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado de produção total', null=True, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Receita pode ser usada para novas ordens', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dias de antecedência para iniciar produção', verbose_name='Lead Time (dias)'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais (legado)', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='name',
            field=models.CharField(help_text='Nome legível da receita', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='output_id',
            field=models.PositiveIntegerField(help_text='ID do produto de saída', verbose_name='ID do Produto'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='output_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Quantidade produzida por execução da receita', max_digits=10, verbose_name='Quantidade de Saída'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='output_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo do produto de saída', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='production_stages',
            field=models.JSONField(blank=True, default=list, help_text="Lista de etapas: ['Mixing', 'Shaping', 'Baking']", verbose_name='Etapas de Produção'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='work_center',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Posição onde a produção acontece', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stockman.position', verbose_name='Centro de Trabalho'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(help_text='Data em que a produção acontecerá', unique=True, verbose_name='Data de Produção'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Onde entregar o produto final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='stockman.position', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Maior = mais prioritário', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantidade aprovada para produzir', max_digits=10, verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado de produção total', null=True, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais (legado)', verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='work_center',
            field=models.ForeignKey(blank=True, help_text='Posição onde a produção acontece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='stockman.position', verbose_name='Centro de Trabalho'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='code',
            field=models.CharField(blank=True, help_text='Identificador único (auto-gerado se vazio)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Onde entregar o produto final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_delivered', to='stockman.position', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais: step_log, completed_by, etc.', verbose_name='Metadados'),
        ),
        migrations.DeleteModel(
            name='HistoricalWorkOrder',
        ),
    ]
