# Generated by Django 5.0.3 on 2025-12-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('craftsman', '0003_add_step_fields'),
        ('stockman', '0005_alter_hold_options_alter_move_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Insumo',
                'verbose_name_plural': 'Categorias de Insumos',
                'db_table': 'craftsman_ingredient_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='baking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade final produzida', max_digits=10, null=True, verbose_name='Produzido'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mixing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade de massa preparada', max_digits=10, null=True, verbose_name='Massa para'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade planejada a produzir', max_digits=10, verbose_name='Planejado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='shaping',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade após processamento/modelagem', max_digits=10, null=True, verbose_name='Processado'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(help_text='ID do material de entrada', verbose_name='ID do Insumo')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade para receita base', max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(default='kg', help_text='kg, L, un, g...', max_length=10, verbose_name='Unidade')),
                ('is_alternative', models.BooleanField(default=False, help_text='Pode ser substituído por outro no grupo', verbose_name='É Alternativa')),
                ('alternative_group', models.CharField(blank=True, help_text='Nome do grupo (ex: gordura)', max_length=50, verbose_name='Grupo de Alternativas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('category', models.ForeignKey(blank=True, help_text='Categoria para agrupamento (ex: Massa, Farinha)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_items', to='craftsman.ingredientcategory', verbose_name='Categoria')),
                ('item_type', models.ForeignKey(help_text='Tipo do material de entrada', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Insumo')),
                ('position', models.ForeignKey(blank=True, help_text='De onde buscar o material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockman.position', verbose_name='Posição')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Item da Receita',
                'verbose_name_plural': 'Itens da Receita',
                'db_table': 'craftsman_recipe_item',
                'ordering': ['recipe', 'category', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='RecipeInput',
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['recipe'], name='craftsman_r_recipe__f5a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['item_type', 'item_id'], name='craftsman_r_item_ty_cc5f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['category'], name='craftsman_r_categor_5f665d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('recipe', 'item_type', 'item_id')},
        ),
    ]
