# Generated by Django 5.2.10 on 2026-01-20 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0007_quantity_decimal_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='historicalrecipe',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='plan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='planitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_by',
            field=models.CharField(blank=True, help_text="Ex: 'user:joao', 'system:scheduler', 'api:pdv-001'", max_length=255, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='external_ref',
            field=models.CharField(blank=True, help_text='ID no sistema de origem, quando aplicável', max_length=255, verbose_name='Referência Externa'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
